package com.family.grabserver.entity;

public class Base {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.id
     *
     * @return the value of base.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.id
     *
     * @param id the value for base.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}