package com.family.grabserver.entity;

public class Base {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.json_md5
     *
     * @mbggenerated
     */
    private String jsonMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base.url_md5
     *
     * @mbggenerated
     */
    private String urlMd5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.id
     *
     * @return the value of base.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.id
     *
     * @param id the value for base.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.json_md5
     *
     * @return the value of base.json_md5
     * @mbggenerated
     */
    public String getJsonMd5() {
        return jsonMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.json_md5
     *
     * @param jsonMd5 the value for base.json_md5
     * @mbggenerated
     */
    public void setJsonMd5(String jsonMd5) {
        this.jsonMd5 = jsonMd5 == null ? null : jsonMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.url
     *
     * @return the value of base.url
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.url
     *
     * @param url the value for base.url
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.url_md5
     *
     * @return the value of base.url_md5
     * @mbggenerated
     */
    public String getUrlMd5() {
        return urlMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.url_md5
     *
     * @param urlMd5 the value for base.url_md5
     * @mbggenerated
     */
    public void setUrlMd5(String urlMd5) {
        this.urlMd5 = urlMd5 == null ? null : urlMd5.trim();
    }
}