package com.family.grabserver.entity;

public class CinemaMaoyan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.nm
     *
     * @mbggenerated
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.ct
     *
     * @mbggenerated
     */
    private String ct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.addr
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.lat
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.lng
     *
     * @mbggenerated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.json_md5
     *
     * @mbggenerated
     */
    private String jsonMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.url_md5
     *
     * @mbggenerated
     */
    private String urlMd5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.id
     *
     * @return the value of cinema_maoyan.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.id
     *
     * @param id the value for cinema_maoyan.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.nm
     *
     * @return the value of cinema_maoyan.nm
     * @mbggenerated
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.nm
     *
     * @param nm the value for cinema_maoyan.nm
     * @mbggenerated
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.ct
     *
     * @return the value of cinema_maoyan.ct
     * @mbggenerated
     */
    public String getCt() {
        return ct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.ct
     *
     * @param ct the value for cinema_maoyan.ct
     * @mbggenerated
     */
    public void setCt(String ct) {
        this.ct = ct == null ? null : ct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.area
     *
     * @return the value of cinema_maoyan.area
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.area
     *
     * @param area the value for cinema_maoyan.area
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.addr
     *
     * @return the value of cinema_maoyan.addr
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.addr
     *
     * @param addr the value for cinema_maoyan.addr
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.lat
     *
     * @return the value of cinema_maoyan.lat
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.lat
     *
     * @param lat the value for cinema_maoyan.lat
     * @mbggenerated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.lng
     *
     * @return the value of cinema_maoyan.lng
     * @mbggenerated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.lng
     *
     * @param lng the value for cinema_maoyan.lng
     * @mbggenerated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.tel
     *
     * @return the value of cinema_maoyan.tel
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.tel
     *
     * @param tel the value for cinema_maoyan.tel
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.json_md5
     *
     * @return the value of cinema_maoyan.json_md5
     * @mbggenerated
     */
    public String getJsonMd5() {
        return jsonMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.json_md5
     *
     * @param jsonMd5 the value for cinema_maoyan.json_md5
     * @mbggenerated
     */
    public void setJsonMd5(String jsonMd5) {
        this.jsonMd5 = jsonMd5 == null ? null : jsonMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.url
     *
     * @return the value of cinema_maoyan.url
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.url
     *
     * @param url the value for cinema_maoyan.url
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.url_md5
     *
     * @return the value of cinema_maoyan.url_md5
     * @mbggenerated
     */
    public String getUrlMd5() {
        return urlMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.url_md5
     *
     * @param urlMd5 the value for cinema_maoyan.url_md5
     * @mbggenerated
     */
    public void setUrlMd5(String urlMd5) {
        this.urlMd5 = urlMd5 == null ? null : urlMd5.trim();
    }
}