package com.family.grabserver.entity;

public class CinemamovieMaoyan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinemamovie_maoyan.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinemamovie_maoyan.cinema_id
     *
     * @mbggenerated
     */
    private Integer cinemaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinemamovie_maoyan.movie_id
     *
     * @mbggenerated
     */
    private Integer movieId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinemamovie_maoyan.id
     *
     * @return the value of cinemamovie_maoyan.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinemamovie_maoyan.id
     *
     * @param id the value for cinemamovie_maoyan.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinemamovie_maoyan.cinema_id
     *
     * @return the value of cinemamovie_maoyan.cinema_id
     *
     * @mbggenerated
     */
    public Integer getCinemaId() {
        return cinemaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinemamovie_maoyan.cinema_id
     *
     * @param cinemaId the value for cinemamovie_maoyan.cinema_id
     *
     * @mbggenerated
     */
    public void setCinemaId(Integer cinemaId) {
        this.cinemaId = cinemaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinemamovie_maoyan.movie_id
     *
     * @return the value of cinemamovie_maoyan.movie_id
     *
     * @mbggenerated
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinemamovie_maoyan.movie_id
     *
     * @param movieId the value for cinemamovie_maoyan.movie_id
     *
     * @mbggenerated
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }
}