package com.family.grabserver.entity;

public class CinemaMtime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.district_id
     *
     * @mbggenerated
     */
    private Integer districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.nm
     *
     * @mbggenerated
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.addr
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.lat
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.lng
     *
     * @mbggenerated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.rating
     *
     * @mbggenerated
     */
    private String rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.has_3d
     *
     * @mbggenerated
     */
    private Boolean has3d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.has_imax
     *
     * @mbggenerated
     */
    private Boolean hasImax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.has_Wifi
     *
     * @mbggenerated
     */
    private Boolean hasWifi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.has_Park
     *
     * @mbggenerated
     */
    private Boolean hasPark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.id
     *
     * @return the value of cinema_mtime.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.id
     *
     * @param id the value for cinema_mtime.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.city_id
     *
     * @return the value of cinema_mtime.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.city_id
     *
     * @param cityId the value for cinema_mtime.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.district_id
     *
     * @return the value of cinema_mtime.district_id
     *
     * @mbggenerated
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.district_id
     *
     * @param districtId the value for cinema_mtime.district_id
     *
     * @mbggenerated
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.nm
     *
     * @return the value of cinema_mtime.nm
     *
     * @mbggenerated
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.nm
     *
     * @param nm the value for cinema_mtime.nm
     *
     * @mbggenerated
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.addr
     *
     * @return the value of cinema_mtime.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.addr
     *
     * @param addr the value for cinema_mtime.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.lat
     *
     * @return the value of cinema_mtime.lat
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.lat
     *
     * @param lat the value for cinema_mtime.lat
     *
     * @mbggenerated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.lng
     *
     * @return the value of cinema_mtime.lng
     *
     * @mbggenerated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.lng
     *
     * @param lng the value for cinema_mtime.lng
     *
     * @mbggenerated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.rating
     *
     * @return the value of cinema_mtime.rating
     *
     * @mbggenerated
     */
    public String getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.rating
     *
     * @param rating the value for cinema_mtime.rating
     *
     * @mbggenerated
     */
    public void setRating(String rating) {
        this.rating = rating == null ? null : rating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.has_3d
     *
     * @return the value of cinema_mtime.has_3d
     *
     * @mbggenerated
     */
    public Boolean getHas3d() {
        return has3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.has_3d
     *
     * @param has3d the value for cinema_mtime.has_3d
     *
     * @mbggenerated
     */
    public void setHas3d(Boolean has3d) {
        this.has3d = has3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.has_imax
     *
     * @return the value of cinema_mtime.has_imax
     *
     * @mbggenerated
     */
    public Boolean getHasImax() {
        return hasImax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.has_imax
     *
     * @param hasImax the value for cinema_mtime.has_imax
     *
     * @mbggenerated
     */
    public void setHasImax(Boolean hasImax) {
        this.hasImax = hasImax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.has_Wifi
     *
     * @return the value of cinema_mtime.has_Wifi
     *
     * @mbggenerated
     */
    public Boolean getHasWifi() {
        return hasWifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.has_Wifi
     *
     * @param hasWifi the value for cinema_mtime.has_Wifi
     *
     * @mbggenerated
     */
    public void setHasWifi(Boolean hasWifi) {
        this.hasWifi = hasWifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.has_Park
     *
     * @return the value of cinema_mtime.has_Park
     *
     * @mbggenerated
     */
    public Boolean getHasPark() {
        return hasPark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.has_Park
     *
     * @param hasPark the value for cinema_mtime.has_Park
     *
     * @mbggenerated
     */
    public void setHasPark(Boolean hasPark) {
        this.hasPark = hasPark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.tel
     *
     * @return the value of cinema_mtime.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.tel
     *
     * @param tel the value for cinema_mtime.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }
}