package com.family.grabserver.entity;

public class CinemamovieMtime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinemamovie_mtime.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinemamovie_mtime.cinema_id
     *
     * @mbggenerated
     */
    private Integer cinemaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinemamovie_mtime.movie_id
     *
     * @mbggenerated
     */
    private Integer movieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinemamovie_mtime.show_dates
     *
     * @mbggenerated
     */
    private String showDates;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinemamovie_mtime.id
     *
     * @return the value of cinemamovie_mtime.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinemamovie_mtime.id
     *
     * @param id the value for cinemamovie_mtime.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinemamovie_mtime.cinema_id
     *
     * @return the value of cinemamovie_mtime.cinema_id
     *
     * @mbggenerated
     */
    public Integer getCinemaId() {
        return cinemaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinemamovie_mtime.cinema_id
     *
     * @param cinemaId the value for cinemamovie_mtime.cinema_id
     *
     * @mbggenerated
     */
    public void setCinemaId(Integer cinemaId) {
        this.cinemaId = cinemaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinemamovie_mtime.movie_id
     *
     * @return the value of cinemamovie_mtime.movie_id
     *
     * @mbggenerated
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinemamovie_mtime.movie_id
     *
     * @param movieId the value for cinemamovie_mtime.movie_id
     *
     * @mbggenerated
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinemamovie_mtime.show_dates
     *
     * @return the value of cinemamovie_mtime.show_dates
     *
     * @mbggenerated
     */
    public String getShowDates() {
        return showDates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinemamovie_mtime.show_dates
     *
     * @param showDates the value for cinemamovie_mtime.show_dates
     *
     * @mbggenerated
     */
    public void setShowDates(String showDates) {
        this.showDates = showDates == null ? null : showDates.trim();
    }
}