package com.family.grabserver.entity;

public class CinemaMaoyanCities {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan_cities.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan_cities.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan_cities.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan_cities.id
     *
     * @return the value of cinema_maoyan_cities.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan_cities.id
     *
     * @param id the value for cinema_maoyan_cities.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan_cities.name
     *
     * @return the value of cinema_maoyan_cities.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan_cities.name
     *
     * @param name the value for cinema_maoyan_cities.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan_cities.pinyin
     *
     * @return the value of cinema_maoyan_cities.pinyin
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan_cities.pinyin
     *
     * @param pinyin the value for cinema_maoyan_cities.pinyin
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }
}