package com.family.grabserver.entity;

public class CinemaMtime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.rating
     *
     * @mbggenerated
     */
    private String rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.has_3d
     *
     * @mbggenerated
     */
    private Boolean has3d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.has_imax
     *
     * @mbggenerated
     */
    private Boolean hasImax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.has_Wifi
     *
     * @mbggenerated
     */
    private Boolean hasWifi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.has_Park
     *
     * @mbggenerated
     */
    private Boolean hasPark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.route
     *
     * @mbggenerated
     */
    private String route;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_mtime.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.id
     *
     * @return the value of cinema_mtime.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.id
     *
     * @param id the value for cinema_mtime.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.city_id
     *
     * @return the value of cinema_mtime.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.city_id
     *
     * @param cityId the value for cinema_mtime.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.area
     *
     * @return the value of cinema_mtime.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.area
     *
     * @param area the value for cinema_mtime.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.name
     *
     * @return the value of cinema_mtime.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.name
     *
     * @param name the value for cinema_mtime.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.address
     *
     * @return the value of cinema_mtime.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.address
     *
     * @param address the value for cinema_mtime.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.latitude
     *
     * @return the value of cinema_mtime.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.latitude
     *
     * @param latitude the value for cinema_mtime.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.longitude
     *
     * @return the value of cinema_mtime.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.longitude
     *
     * @param longitude the value for cinema_mtime.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.rating
     *
     * @return the value of cinema_mtime.rating
     *
     * @mbggenerated
     */
    public String getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.rating
     *
     * @param rating the value for cinema_mtime.rating
     *
     * @mbggenerated
     */
    public void setRating(String rating) {
        this.rating = rating == null ? null : rating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.has_3d
     *
     * @return the value of cinema_mtime.has_3d
     *
     * @mbggenerated
     */
    public Boolean getHas3d() {
        return has3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.has_3d
     *
     * @param has3d the value for cinema_mtime.has_3d
     *
     * @mbggenerated
     */
    public void setHas3d(Boolean has3d) {
        this.has3d = has3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.has_imax
     *
     * @return the value of cinema_mtime.has_imax
     *
     * @mbggenerated
     */
    public Boolean getHasImax() {
        return hasImax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.has_imax
     *
     * @param hasImax the value for cinema_mtime.has_imax
     *
     * @mbggenerated
     */
    public void setHasImax(Boolean hasImax) {
        this.hasImax = hasImax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.has_Wifi
     *
     * @return the value of cinema_mtime.has_Wifi
     *
     * @mbggenerated
     */
    public Boolean getHasWifi() {
        return hasWifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.has_Wifi
     *
     * @param hasWifi the value for cinema_mtime.has_Wifi
     *
     * @mbggenerated
     */
    public void setHasWifi(Boolean hasWifi) {
        this.hasWifi = hasWifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.has_Park
     *
     * @return the value of cinema_mtime.has_Park
     *
     * @mbggenerated
     */
    public Boolean getHasPark() {
        return hasPark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.has_Park
     *
     * @param hasPark the value for cinema_mtime.has_Park
     *
     * @mbggenerated
     */
    public void setHasPark(Boolean hasPark) {
        this.hasPark = hasPark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.route
     *
     * @return the value of cinema_mtime.route
     *
     * @mbggenerated
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.route
     *
     * @param route the value for cinema_mtime.route
     *
     * @mbggenerated
     */
    public void setRoute(String route) {
        this.route = route == null ? null : route.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_mtime.tel
     *
     * @return the value of cinema_mtime.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_mtime.tel
     *
     * @param tel the value for cinema_mtime.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }
}