package com.family.grabserver.entity;

public class CinemaMaoyan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.sell
     *
     * @mbggenerated
     */
    private Boolean sell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.preferential
     *
     * @mbggenerated
     */
    private Boolean preferential;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.has_imax
     *
     * @mbggenerated
     */
    private Boolean hasImax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema_maoyan.json_md5
     *
     * @mbggenerated
     */
    private String jsonMd5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.id
     *
     * @return the value of cinema_maoyan.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.id
     *
     * @param id the value for cinema_maoyan.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.city_id
     *
     * @return the value of cinema_maoyan.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.city_id
     *
     * @param cityId the value for cinema_maoyan.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.name
     *
     * @return the value of cinema_maoyan.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.name
     *
     * @param name the value for cinema_maoyan.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.area
     *
     * @return the value of cinema_maoyan.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.area
     *
     * @param area the value for cinema_maoyan.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.address
     *
     * @return the value of cinema_maoyan.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.address
     *
     * @param address the value for cinema_maoyan.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.latitude
     *
     * @return the value of cinema_maoyan.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.latitude
     *
     * @param latitude the value for cinema_maoyan.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.longitude
     *
     * @return the value of cinema_maoyan.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.longitude
     *
     * @param longitude the value for cinema_maoyan.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.sell
     *
     * @return the value of cinema_maoyan.sell
     *
     * @mbggenerated
     */
    public Boolean getSell() {
        return sell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.sell
     *
     * @param sell the value for cinema_maoyan.sell
     *
     * @mbggenerated
     */
    public void setSell(Boolean sell) {
        this.sell = sell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.preferential
     *
     * @return the value of cinema_maoyan.preferential
     *
     * @mbggenerated
     */
    public Boolean getPreferential() {
        return preferential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.preferential
     *
     * @param preferential the value for cinema_maoyan.preferential
     *
     * @mbggenerated
     */
    public void setPreferential(Boolean preferential) {
        this.preferential = preferential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.has_imax
     *
     * @return the value of cinema_maoyan.has_imax
     *
     * @mbggenerated
     */
    public Boolean getHasImax() {
        return hasImax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.has_imax
     *
     * @param hasImax the value for cinema_maoyan.has_imax
     *
     * @mbggenerated
     */
    public void setHasImax(Boolean hasImax) {
        this.hasImax = hasImax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.tel
     *
     * @return the value of cinema_maoyan.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.tel
     *
     * @param tel the value for cinema_maoyan.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema_maoyan.json_md5
     *
     * @return the value of cinema_maoyan.json_md5
     *
     * @mbggenerated
     */
    public String getJsonMd5() {
        return jsonMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema_maoyan.json_md5
     *
     * @param jsonMd5 the value for cinema_maoyan.json_md5
     *
     * @mbggenerated
     */
    public void setJsonMd5(String jsonMd5) {
        this.jsonMd5 = jsonMd5 == null ? null : jsonMd5.trim();
    }
}