package com.family.grabserver.entity;

public class MaoyanCinema {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maoyan_cinema.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maoyan_cinema.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maoyan_cinema.urlMd5
     *
     * @mbggenerated
     */
    private String urlmd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maoyan_cinema.context
     *
     * @mbggenerated
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maoyan_cinema.id
     *
     * @return the value of maoyan_cinema.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maoyan_cinema.id
     *
     * @param id the value for maoyan_cinema.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maoyan_cinema.url
     *
     * @return the value of maoyan_cinema.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maoyan_cinema.url
     *
     * @param url the value for maoyan_cinema.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maoyan_cinema.urlMd5
     *
     * @return the value of maoyan_cinema.urlMd5
     *
     * @mbggenerated
     */
    public String getUrlmd5() {
        return urlmd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maoyan_cinema.urlMd5
     *
     * @param urlmd5 the value for maoyan_cinema.urlMd5
     *
     * @mbggenerated
     */
    public void setUrlmd5(String urlmd5) {
        this.urlmd5 = urlmd5 == null ? null : urlmd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maoyan_cinema.context
     *
     * @return the value of maoyan_cinema.context
     *
     * @mbggenerated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maoyan_cinema.context
     *
     * @param context the value for maoyan_cinema.context
     *
     * @mbggenerated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}