package com.family.grabserver.entity;

public class MovieshowingMaoyan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.rating
     *
     * @mbggenerated
     */
    private String rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.is_imax
     *
     * @mbggenerated
     */
    private Boolean isImax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.is_3d
     *
     * @mbggenerated
     */
    private Boolean is3d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.directors
     *
     * @mbggenerated
     */
    private String directors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.actors
     *
     * @mbggenerated
     */
    private String actors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.runTime
     *
     * @mbggenerated
     */
    private String runtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.ver
     *
     * @mbggenerated
     */
    private String ver;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.id
     *
     * @return the value of movieshowing_maoyan.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.id
     *
     * @param id the value for movieshowing_maoyan.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.name
     *
     * @return the value of movieshowing_maoyan.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.name
     *
     * @param name the value for movieshowing_maoyan.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.image
     *
     * @return the value of movieshowing_maoyan.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.image
     *
     * @param image the value for movieshowing_maoyan.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.rating
     *
     * @return the value of movieshowing_maoyan.rating
     *
     * @mbggenerated
     */
    public String getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.rating
     *
     * @param rating the value for movieshowing_maoyan.rating
     *
     * @mbggenerated
     */
    public void setRating(String rating) {
        this.rating = rating == null ? null : rating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.is_imax
     *
     * @return the value of movieshowing_maoyan.is_imax
     *
     * @mbggenerated
     */
    public Boolean getIsImax() {
        return isImax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.is_imax
     *
     * @param isImax the value for movieshowing_maoyan.is_imax
     *
     * @mbggenerated
     */
    public void setIsImax(Boolean isImax) {
        this.isImax = isImax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.is_3d
     *
     * @return the value of movieshowing_maoyan.is_3d
     *
     * @mbggenerated
     */
    public Boolean getIs3d() {
        return is3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.is_3d
     *
     * @param is3d the value for movieshowing_maoyan.is_3d
     *
     * @mbggenerated
     */
    public void setIs3d(Boolean is3d) {
        this.is3d = is3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.directors
     *
     * @return the value of movieshowing_maoyan.directors
     *
     * @mbggenerated
     */
    public String getDirectors() {
        return directors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.directors
     *
     * @param directors the value for movieshowing_maoyan.directors
     *
     * @mbggenerated
     */
    public void setDirectors(String directors) {
        this.directors = directors == null ? null : directors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.actors
     *
     * @return the value of movieshowing_maoyan.actors
     *
     * @mbggenerated
     */
    public String getActors() {
        return actors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.actors
     *
     * @param actors the value for movieshowing_maoyan.actors
     *
     * @mbggenerated
     */
    public void setActors(String actors) {
        this.actors = actors == null ? null : actors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.type
     *
     * @return the value of movieshowing_maoyan.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.type
     *
     * @param type the value for movieshowing_maoyan.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.content
     *
     * @return the value of movieshowing_maoyan.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.content
     *
     * @param content the value for movieshowing_maoyan.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.runTime
     *
     * @return the value of movieshowing_maoyan.runTime
     *
     * @mbggenerated
     */
    public String getRuntime() {
        return runtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.runTime
     *
     * @param runtime the value for movieshowing_maoyan.runTime
     *
     * @mbggenerated
     */
    public void setRuntime(String runtime) {
        this.runtime = runtime == null ? null : runtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.ver
     *
     * @return the value of movieshowing_maoyan.ver
     *
     * @mbggenerated
     */
    public String getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.ver
     *
     * @param ver the value for movieshowing_maoyan.ver
     *
     * @mbggenerated
     */
    public void setVer(String ver) {
        this.ver = ver == null ? null : ver.trim();
    }
}