package com.family.grabserver.entity;

public class MovieshowingMaoyan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.nm
     *
     * @mbggenerated
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.sc
     *
     * @mbggenerated
     */
    private String sc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.src
     *
     * @mbggenerated
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.imax
     *
     * @mbggenerated
     */
    private Boolean imax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.is3d
     *
     * @mbggenerated
     */
    private Boolean is3d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.dir
     *
     * @mbggenerated
     */
    private String dir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.star
     *
     * @mbggenerated
     */
    private String star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.cat
     *
     * @mbggenerated
     */
    private String cat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.scm
     *
     * @mbggenerated
     */
    private String scm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.dur
     *
     * @mbggenerated
     */
    private String dur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_maoyan.ver
     *
     * @mbggenerated
     */
    private String ver;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.id
     *
     * @return the value of movieshowing_maoyan.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.id
     *
     * @param id the value for movieshowing_maoyan.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.nm
     *
     * @return the value of movieshowing_maoyan.nm
     *
     * @mbggenerated
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.nm
     *
     * @param nm the value for movieshowing_maoyan.nm
     *
     * @mbggenerated
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.img
     *
     * @return the value of movieshowing_maoyan.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.img
     *
     * @param img the value for movieshowing_maoyan.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.sc
     *
     * @return the value of movieshowing_maoyan.sc
     *
     * @mbggenerated
     */
    public String getSc() {
        return sc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.sc
     *
     * @param sc the value for movieshowing_maoyan.sc
     *
     * @mbggenerated
     */
    public void setSc(String sc) {
        this.sc = sc == null ? null : sc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.src
     *
     * @return the value of movieshowing_maoyan.src
     *
     * @mbggenerated
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.src
     *
     * @param src the value for movieshowing_maoyan.src
     *
     * @mbggenerated
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.imax
     *
     * @return the value of movieshowing_maoyan.imax
     *
     * @mbggenerated
     */
    public Boolean getImax() {
        return imax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.imax
     *
     * @param imax the value for movieshowing_maoyan.imax
     *
     * @mbggenerated
     */
    public void setImax(Boolean imax) {
        this.imax = imax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.is3d
     *
     * @return the value of movieshowing_maoyan.is3d
     *
     * @mbggenerated
     */
    public Boolean getIs3d() {
        return is3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.is3d
     *
     * @param is3d the value for movieshowing_maoyan.is3d
     *
     * @mbggenerated
     */
    public void setIs3d(Boolean is3d) {
        this.is3d = is3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.dir
     *
     * @return the value of movieshowing_maoyan.dir
     *
     * @mbggenerated
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.dir
     *
     * @param dir the value for movieshowing_maoyan.dir
     *
     * @mbggenerated
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.star
     *
     * @return the value of movieshowing_maoyan.star
     *
     * @mbggenerated
     */
    public String getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.star
     *
     * @param star the value for movieshowing_maoyan.star
     *
     * @mbggenerated
     */
    public void setStar(String star) {
        this.star = star == null ? null : star.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.cat
     *
     * @return the value of movieshowing_maoyan.cat
     *
     * @mbggenerated
     */
    public String getCat() {
        return cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.cat
     *
     * @param cat the value for movieshowing_maoyan.cat
     *
     * @mbggenerated
     */
    public void setCat(String cat) {
        this.cat = cat == null ? null : cat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.scm
     *
     * @return the value of movieshowing_maoyan.scm
     *
     * @mbggenerated
     */
    public String getScm() {
        return scm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.scm
     *
     * @param scm the value for movieshowing_maoyan.scm
     *
     * @mbggenerated
     */
    public void setScm(String scm) {
        this.scm = scm == null ? null : scm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.dur
     *
     * @return the value of movieshowing_maoyan.dur
     *
     * @mbggenerated
     */
    public String getDur() {
        return dur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.dur
     *
     * @param dur the value for movieshowing_maoyan.dur
     *
     * @mbggenerated
     */
    public void setDur(String dur) {
        this.dur = dur == null ? null : dur.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_maoyan.ver
     *
     * @return the value of movieshowing_maoyan.ver
     *
     * @mbggenerated
     */
    public String getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_maoyan.ver
     *
     * @param ver the value for movieshowing_maoyan.ver
     *
     * @mbggenerated
     */
    public void setVer(String ver) {
        this.ver = ver == null ? null : ver.trim();
    }
}