package com.family.grabserver.entity;

public class MovieshowingMtime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.nm
     *
     * @mbggenerated
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.sc
     *
     * @mbggenerated
     */
    private String sc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.imax
     *
     * @mbggenerated
     */
    private Boolean imax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.is3d
     *
     * @mbggenerated
     */
    private Boolean is3d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.dir
     *
     * @mbggenerated
     */
    private String dir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.star
     *
     * @mbggenerated
     */
    private String star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.cat
     *
     * @mbggenerated
     */
    private String cat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.scm
     *
     * @mbggenerated
     */
    private String scm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieshowing_mtime.dur
     *
     * @mbggenerated
     */
    private String dur;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.id
     *
     * @return the value of movieshowing_mtime.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.id
     *
     * @param id the value for movieshowing_mtime.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.nm
     *
     * @return the value of movieshowing_mtime.nm
     * @mbggenerated
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.nm
     *
     * @param nm the value for movieshowing_mtime.nm
     * @mbggenerated
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.img
     *
     * @return the value of movieshowing_mtime.img
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.img
     *
     * @param img the value for movieshowing_mtime.img
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.sc
     *
     * @return the value of movieshowing_mtime.sc
     * @mbggenerated
     */
    public String getSc() {
        return sc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.sc
     *
     * @param sc the value for movieshowing_mtime.sc
     * @mbggenerated
     */
    public void setSc(String sc) {
        this.sc = sc == null ? null : sc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.imax
     *
     * @return the value of movieshowing_mtime.imax
     * @mbggenerated
     */
    public Boolean getImax() {
        return imax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.imax
     *
     * @param imax the value for movieshowing_mtime.imax
     * @mbggenerated
     */
    public void setImax(Boolean imax) {
        this.imax = imax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.is3d
     *
     * @return the value of movieshowing_mtime.is3d
     * @mbggenerated
     */
    public Boolean getIs3d() {
        return is3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.is3d
     *
     * @param is3d the value for movieshowing_mtime.is3d
     * @mbggenerated
     */
    public void setIs3d(Boolean is3d) {
        this.is3d = is3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.dir
     *
     * @return the value of movieshowing_mtime.dir
     * @mbggenerated
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.dir
     *
     * @param dir the value for movieshowing_mtime.dir
     * @mbggenerated
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.star
     *
     * @return the value of movieshowing_mtime.star
     * @mbggenerated
     */
    public String getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.star
     *
     * @param star the value for movieshowing_mtime.star
     * @mbggenerated
     */
    public void setStar(String star) {
        this.star = star == null ? null : star.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.cat
     *
     * @return the value of movieshowing_mtime.cat
     * @mbggenerated
     */
    public String getCat() {
        return cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.cat
     *
     * @param cat the value for movieshowing_mtime.cat
     * @mbggenerated
     */
    public void setCat(String cat) {
        this.cat = cat == null ? null : cat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.scm
     *
     * @return the value of movieshowing_mtime.scm
     * @mbggenerated
     */
    public String getScm() {
        return scm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.scm
     *
     * @param scm the value for movieshowing_mtime.scm
     * @mbggenerated
     */
    public void setScm(String scm) {
        this.scm = scm == null ? null : scm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieshowing_mtime.dur
     *
     * @return the value of movieshowing_mtime.dur
     * @mbggenerated
     */
    public String getDur() {
        return dur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieshowing_mtime.dur
     *
     * @param dur the value for movieshowing_mtime.dur
     * @mbggenerated
     */
    public void setDur(String dur) {
        this.dur = dur == null ? null : dur.trim();
    }
}