package com.family.grabserver.entity;

import java.util.Date;

public class ScreeningMaoyan {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.cinema_id
   *
   * @mbggenerated
   */
  private Integer cinemaId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.movie_id
   *
   * @mbggenerated
   */
  private Integer movieId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.show_date
   *
   * @mbggenerated
   */
  private Date showDate;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.start_time
   *
   * @mbggenerated
   */
  private Date startTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.end_time
   *
   * @mbggenerated
   */
  private Date endTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.language
   *
   * @mbggenerated
   */
  private String language;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.hall
   *
   * @mbggenerated
   */
  private String hall;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.version
   *
   * @mbggenerated
   */
  private String version;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.sale_price
   *
   * @mbggenerated
   */
  private Float salePrice;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.cinema_price
   *
   * @mbggenerated
   */
  private Float cinemaPrice;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column screening_maoyan.ticket_url
   *
   * @mbggenerated
   */
  private String ticketUrl;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.id
   *
   * @return the value of screening_maoyan.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.id
   *
   * @param id the value for screening_maoyan.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.cinema_id
   *
   * @return the value of screening_maoyan.cinema_id
   * @mbggenerated
   */
  public Integer getCinemaId() {
    return cinemaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.cinema_id
   *
   * @param cinemaId the value for screening_maoyan.cinema_id
   * @mbggenerated
   */
  public void setCinemaId(Integer cinemaId) {
    this.cinemaId = cinemaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.movie_id
   *
   * @return the value of screening_maoyan.movie_id
   * @mbggenerated
   */
  public Integer getMovieId() {
    return movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.movie_id
   *
   * @param movieId the value for screening_maoyan.movie_id
   * @mbggenerated
   */
  public void setMovieId(Integer movieId) {
    this.movieId = movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.show_date
   *
   * @return the value of screening_maoyan.show_date
   * @mbggenerated
   */
  public Date getShowDate() {
    return showDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.show_date
   *
   * @param showDate the value for screening_maoyan.show_date
   * @mbggenerated
   */
  public void setShowDate(Date showDate) {
    this.showDate = showDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.start_time
   *
   * @return the value of screening_maoyan.start_time
   * @mbggenerated
   */
  public Date getStartTime() {
    return startTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.start_time
   *
   * @param startTime the value for screening_maoyan.start_time
   * @mbggenerated
   */
  public void setStartTime(Date startTime) {
    this.startTime = startTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.end_time
   *
   * @return the value of screening_maoyan.end_time
   * @mbggenerated
   */
  public Date getEndTime() {
    return endTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.end_time
   *
   * @param endTime the value for screening_maoyan.end_time
   * @mbggenerated
   */
  public void setEndTime(Date endTime) {
    this.endTime = endTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.language
   *
   * @return the value of screening_maoyan.language
   * @mbggenerated
   */
  public String getLanguage() {
    return language;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.language
   *
   * @param language the value for screening_maoyan.language
   * @mbggenerated
   */
  public void setLanguage(String language) {
    this.language = language == null ? null : language.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.hall
   *
   * @return the value of screening_maoyan.hall
   * @mbggenerated
   */
  public String getHall() {
    return hall;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.hall
   *
   * @param hall the value for screening_maoyan.hall
   * @mbggenerated
   */
  public void setHall(String hall) {
    this.hall = hall == null ? null : hall.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.version
   *
   * @return the value of screening_maoyan.version
   * @mbggenerated
   */
  public String getVersion() {
    return version;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.version
   *
   * @param version the value for screening_maoyan.version
   * @mbggenerated
   */
  public void setVersion(String version) {
    this.version = version == null ? null : version.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.sale_price
   *
   * @return the value of screening_maoyan.sale_price
   * @mbggenerated
   */
  public Float getSalePrice() {
    return salePrice;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.sale_price
   *
   * @param salePrice the value for screening_maoyan.sale_price
   * @mbggenerated
   */
  public void setSalePrice(Float salePrice) {
    this.salePrice = salePrice;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.cinema_price
   *
   * @return the value of screening_maoyan.cinema_price
   * @mbggenerated
   */
  public Float getCinemaPrice() {
    return cinemaPrice;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.cinema_price
   *
   * @param cinemaPrice the value for screening_maoyan.cinema_price
   * @mbggenerated
   */
  public void setCinemaPrice(Float cinemaPrice) {
    this.cinemaPrice = cinemaPrice;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column screening_maoyan.ticket_url
   *
   * @return the value of screening_maoyan.ticket_url
   * @mbggenerated
   */
  public String getTicketUrl() {
    return ticketUrl;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column screening_maoyan.ticket_url
   *
   * @param ticketUrl the value for screening_maoyan.ticket_url
   * @mbggenerated
   */
  public void setTicketUrl(String ticketUrl) {
    this.ticketUrl = ticketUrl == null ? null : ticketUrl.trim();
  }
}
