package com.family.grabserver.entity;

import java.util.Date;

public class ShowPlanMaoyan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.cinema_id
     *
     * @mbggenerated
     */
    private Integer cinemaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.movie_id
     *
     * @mbggenerated
     */
    private Integer movieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.dt
     *
     * @mbggenerated
     */
    private Date dt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.tm
     *
     * @mbggenerated
     */
    private Date tm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.end
     *
     * @mbggenerated
     */
    private Date end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.lang
     *
     * @mbggenerated
     */
    private String lang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.th
     *
     * @mbggenerated
     */
    private String th;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.tp
     *
     * @mbggenerated
     */
    private String tp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.sellPrStr
     *
     * @mbggenerated
     */
    private String sellprstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column show_plan_maoyan.prStr
     *
     * @mbggenerated
     */
    private String prstr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.id
     *
     * @return the value of show_plan_maoyan.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.id
     *
     * @param id the value for show_plan_maoyan.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.cinema_id
     *
     * @return the value of show_plan_maoyan.cinema_id
     * @mbggenerated
     */
    public Integer getCinemaId() {
        return cinemaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.cinema_id
     *
     * @param cinemaId the value for show_plan_maoyan.cinema_id
     * @mbggenerated
     */
    public void setCinemaId(Integer cinemaId) {
        this.cinemaId = cinemaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.movie_id
     *
     * @return the value of show_plan_maoyan.movie_id
     * @mbggenerated
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.movie_id
     *
     * @param movieId the value for show_plan_maoyan.movie_id
     * @mbggenerated
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.dt
     *
     * @return the value of show_plan_maoyan.dt
     * @mbggenerated
     */
    public Date getDt() {
        return dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.dt
     *
     * @param dt the value for show_plan_maoyan.dt
     * @mbggenerated
     */
    public void setDt(Date dt) {
        this.dt = dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.tm
     *
     * @return the value of show_plan_maoyan.tm
     * @mbggenerated
     */
    public Date getTm() {
        return tm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.tm
     *
     * @param tm the value for show_plan_maoyan.tm
     * @mbggenerated
     */
    public void setTm(Date tm) {
        this.tm = tm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.end
     *
     * @return the value of show_plan_maoyan.end
     * @mbggenerated
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.end
     *
     * @param end the value for show_plan_maoyan.end
     * @mbggenerated
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.lang
     *
     * @return the value of show_plan_maoyan.lang
     * @mbggenerated
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.lang
     *
     * @param lang the value for show_plan_maoyan.lang
     * @mbggenerated
     */
    public void setLang(String lang) {
        this.lang = lang == null ? null : lang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.th
     *
     * @return the value of show_plan_maoyan.th
     * @mbggenerated
     */
    public String getTh() {
        return th;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.th
     *
     * @param th the value for show_plan_maoyan.th
     * @mbggenerated
     */
    public void setTh(String th) {
        this.th = th == null ? null : th.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.tp
     *
     * @return the value of show_plan_maoyan.tp
     * @mbggenerated
     */
    public String getTp() {
        return tp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.tp
     *
     * @param tp the value for show_plan_maoyan.tp
     * @mbggenerated
     */
    public void setTp(String tp) {
        this.tp = tp == null ? null : tp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.sellPrStr
     *
     * @return the value of show_plan_maoyan.sellPrStr
     * @mbggenerated
     */
    public String getSellprstr() {
        return sellprstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.sellPrStr
     *
     * @param sellprstr the value for show_plan_maoyan.sellPrStr
     * @mbggenerated
     */
    public void setSellprstr(String sellprstr) {
        this.sellprstr = sellprstr == null ? null : sellprstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column show_plan_maoyan.prStr
     *
     * @return the value of show_plan_maoyan.prStr
     * @mbggenerated
     */
    public String getPrstr() {
        return prstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column show_plan_maoyan.prStr
     *
     * @param prstr the value for show_plan_maoyan.prStr
     * @mbggenerated
     */
    public void setPrstr(String prstr) {
        this.prstr = prstr == null ? null : prstr.trim();
    }
}