package com.family.grabserver.entity;

import java.util.Date;

public class ShowplanMtime {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.cinema_id
   *
   * @mbggenerated
   */
  private Integer cinemaId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.movie_id
   *
   * @mbggenerated
   */
  private Integer movieId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.show_date
   *
   * @mbggenerated
   */
  private Date showDate;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.start_time
   *
   * @mbggenerated
   */
  private Date startTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.end_time
   *
   * @mbggenerated
   */
  private Date endTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.language
   *
   * @mbggenerated
   */
  private String language;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.hall
   *
   * @mbggenerated
   */
  private String hall;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.versionDesc
   *
   * @mbggenerated
   */
  private String versiondesc;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.salePrice
   *
   * @mbggenerated
   */
  private Float saleprice;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.cinemaPrice
   *
   * @mbggenerated
   */
  private Float cinemaprice;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column showplan_mtime.ticket_url
   *
   * @mbggenerated
   */
  private String ticketUrl;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.id
   *
   * @return the value of showplan_mtime.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.id
   *
   * @param id the value for showplan_mtime.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.cinema_id
   *
   * @return the value of showplan_mtime.cinema_id
   * @mbggenerated
   */
  public Integer getCinemaId() {
    return cinemaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.cinema_id
   *
   * @param cinemaId the value for showplan_mtime.cinema_id
   * @mbggenerated
   */
  public void setCinemaId(Integer cinemaId) {
    this.cinemaId = cinemaId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.movie_id
   *
   * @return the value of showplan_mtime.movie_id
   * @mbggenerated
   */
  public Integer getMovieId() {
    return movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.movie_id
   *
   * @param movieId the value for showplan_mtime.movie_id
   * @mbggenerated
   */
  public void setMovieId(Integer movieId) {
    this.movieId = movieId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.show_date
   *
   * @return the value of showplan_mtime.show_date
   * @mbggenerated
   */
  public Date getShowDate() {
    return showDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.show_date
   *
   * @param showDate the value for showplan_mtime.show_date
   * @mbggenerated
   */
  public void setShowDate(Date showDate) {
    this.showDate = showDate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.start_time
   *
   * @return the value of showplan_mtime.start_time
   * @mbggenerated
   */
  public Date getStartTime() {
    return startTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.start_time
   *
   * @param startTime the value for showplan_mtime.start_time
   * @mbggenerated
   */
  public void setStartTime(Date startTime) {
    this.startTime = startTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.end_time
   *
   * @return the value of showplan_mtime.end_time
   * @mbggenerated
   */
  public Date getEndTime() {
    return endTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.end_time
   *
   * @param endTime the value for showplan_mtime.end_time
   * @mbggenerated
   */
  public void setEndTime(Date endTime) {
    this.endTime = endTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.language
   *
   * @return the value of showplan_mtime.language
   * @mbggenerated
   */
  public String getLanguage() {
    return language;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.language
   *
   * @param language the value for showplan_mtime.language
   * @mbggenerated
   */
  public void setLanguage(String language) {
    this.language = language == null ? null : language.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.hall
   *
   * @return the value of showplan_mtime.hall
   * @mbggenerated
   */
  public String getHall() {
    return hall;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.hall
   *
   * @param hall the value for showplan_mtime.hall
   * @mbggenerated
   */
  public void setHall(String hall) {
    this.hall = hall == null ? null : hall.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.versionDesc
   *
   * @return the value of showplan_mtime.versionDesc
   * @mbggenerated
   */
  public String getVersiondesc() {
    return versiondesc;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.versionDesc
   *
   * @param versiondesc the value for showplan_mtime.versionDesc
   * @mbggenerated
   */
  public void setVersiondesc(String versiondesc) {
    this.versiondesc = versiondesc == null ? null : versiondesc.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.salePrice
   *
   * @return the value of showplan_mtime.salePrice
   * @mbggenerated
   */
  public Float getSaleprice() {
    return saleprice;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.salePrice
   *
   * @param saleprice the value for showplan_mtime.salePrice
   * @mbggenerated
   */
  public void setSaleprice(Float saleprice) {
    this.saleprice = saleprice;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.cinemaPrice
   *
   * @return the value of showplan_mtime.cinemaPrice
   * @mbggenerated
   */
  public Float getCinemaprice() {
    return cinemaprice;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.cinemaPrice
   *
   * @param cinemaprice the value for showplan_mtime.cinemaPrice
   * @mbggenerated
   */
  public void setCinemaprice(Float cinemaprice) {
    this.cinemaprice = cinemaprice;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column showplan_mtime.ticket_url
   *
   * @return the value of showplan_mtime.ticket_url
   * @mbggenerated
   */
  public String getTicketUrl() {
    return ticketUrl;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column showplan_mtime.ticket_url
   *
   * @param ticketUrl the value for showplan_mtime.ticket_url
   * @mbggenerated
   */
  public void setTicketUrl(String ticketUrl) {
    this.ticketUrl = ticketUrl == null ? null : ticketUrl.trim();
  }
}
