package com.family.grabserver.entity;

public class ViewMovieshowing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.nm
     *
     * @mbggenerated
     */
    private String nm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.sc
     *
     * @mbggenerated
     */
    private String sc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.has_imax
     *
     * @mbggenerated
     */
    private Byte hasImax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.has_3d
     *
     * @mbggenerated
     */
    private Byte has3d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.dir
     *
     * @mbggenerated
     */
    private String dir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.cat
     *
     * @mbggenerated
     */
    private String cat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.dur
     *
     * @mbggenerated
     */
    private String dur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.Name_exp_10
     *
     * @mbggenerated
     */
    private String nameExp10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.star
     *
     * @mbggenerated
     */
    private String star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_movieshowing.scm
     *
     * @mbggenerated
     */
    private String scm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.nm
     *
     * @return the value of view_movieshowing.nm
     * @mbggenerated
     */
    public String getNm() {
        return nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.nm
     *
     * @param nm the value for view_movieshowing.nm
     * @mbggenerated
     */
    public void setNm(String nm) {
        this.nm = nm == null ? null : nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.sc
     *
     * @return the value of view_movieshowing.sc
     * @mbggenerated
     */
    public String getSc() {
        return sc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.sc
     *
     * @param sc the value for view_movieshowing.sc
     * @mbggenerated
     */
    public void setSc(String sc) {
        this.sc = sc == null ? null : sc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.has_imax
     *
     * @return the value of view_movieshowing.has_imax
     * @mbggenerated
     */
    public Byte getHasImax() {
        return hasImax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.has_imax
     *
     * @param hasImax the value for view_movieshowing.has_imax
     * @mbggenerated
     */
    public void setHasImax(Byte hasImax) {
        this.hasImax = hasImax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.has_3d
     *
     * @return the value of view_movieshowing.has_3d
     * @mbggenerated
     */
    public Byte getHas3d() {
        return has3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.has_3d
     *
     * @param has3d the value for view_movieshowing.has_3d
     * @mbggenerated
     */
    public void setHas3d(Byte has3d) {
        this.has3d = has3d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.dir
     *
     * @return the value of view_movieshowing.dir
     * @mbggenerated
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.dir
     *
     * @param dir the value for view_movieshowing.dir
     * @mbggenerated
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.cat
     *
     * @return the value of view_movieshowing.cat
     * @mbggenerated
     */
    public String getCat() {
        return cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.cat
     *
     * @param cat the value for view_movieshowing.cat
     * @mbggenerated
     */
    public void setCat(String cat) {
        this.cat = cat == null ? null : cat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.dur
     *
     * @return the value of view_movieshowing.dur
     * @mbggenerated
     */
    public String getDur() {
        return dur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.dur
     *
     * @param dur the value for view_movieshowing.dur
     * @mbggenerated
     */
    public void setDur(String dur) {
        this.dur = dur == null ? null : dur.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.Name_exp_10
     *
     * @return the value of view_movieshowing.Name_exp_10
     * @mbggenerated
     */
    public String getNameExp10() {
        return nameExp10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.Name_exp_10
     *
     * @param nameExp10 the value for view_movieshowing.Name_exp_10
     * @mbggenerated
     */
    public void setNameExp10(String nameExp10) {
        this.nameExp10 = nameExp10 == null ? null : nameExp10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.img
     *
     * @return the value of view_movieshowing.img
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.img
     *
     * @param img the value for view_movieshowing.img
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.star
     *
     * @return the value of view_movieshowing.star
     * @mbggenerated
     */
    public String getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.star
     *
     * @param star the value for view_movieshowing.star
     * @mbggenerated
     */
    public void setStar(String star) {
        this.star = star == null ? null : star.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_movieshowing.scm
     *
     * @return the value of view_movieshowing.scm
     * @mbggenerated
     */
    public String getScm() {
        return scm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_movieshowing.scm
     *
     * @param scm the value for view_movieshowing.scm
     * @mbggenerated
     */
    public void setScm(String scm) {
        this.scm = scm == null ? null : scm.trim();
    }
}