package com.family.grabserver.mapper;

import com.family.grabserver.entity.CinemamovieMtime;

import java.util.List;

public interface CinemamovieMtimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinemamovie_mtime
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinemamovie_mtime
     *
     * @mbggenerated
     */
    int insert(CinemamovieMtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinemamovie_mtime
     *
     * @mbggenerated
     */
    CinemamovieMtime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinemamovie_mtime
     *
     * @mbggenerated
     */
    List<CinemamovieMtime> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinemamovie_mtime
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CinemamovieMtime record);
}
