package com.family.grabserver.mapper;

import com.family.grabserver.entity.CinemaMaoyanFeatures;

import java.util.List;

public interface CinemaMaoyanFeaturesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan_features
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan_features
     *
     * @mbggenerated
     */
    int insert(CinemaMaoyanFeatures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan_features
     *
     * @mbggenerated
     */
    CinemaMaoyanFeatures selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan_features
     *
     * @mbggenerated
     */
    List<CinemaMaoyanFeatures> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan_features
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CinemaMaoyanFeatures record);
}