package com.family.grabserver.mapper;

import com.family.grabserver.entity.CinemaMaoyanCities;

import java.util.List;

public interface CinemaMaoyanCitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan_cities
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan_cities
     *
     * @mbggenerated
     */
    int insert(CinemaMaoyanCities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan_cities
     *
     * @mbggenerated
     */
    CinemaMaoyanCities selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan_cities
     *
     * @mbggenerated
     */
    List<CinemaMaoyanCities> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan_cities
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CinemaMaoyanCities record);
}