package com.family.grabserver.mapper;

import com.family.grabserver.entity.CinemaMaoyan;

import java.util.List;

public interface CinemaMaoyanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan
     *
     * @mbggenerated
     */
    int insert(CinemaMaoyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan
     *
     * @mbggenerated
     */
    CinemaMaoyan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan
     *
     * @mbggenerated
     */
    List<CinemaMaoyan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_maoyan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CinemaMaoyan record);
}
