package com.family.grabserver.mapper;

import com.family.grabserver.entity.CinemaMtime;

import java.util.List;

public interface CinemaMtimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_mtime
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_mtime
     *
     * @mbggenerated
     */
    int insert(CinemaMtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_mtime
     *
     * @mbggenerated
     */
    CinemaMtime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_mtime
     *
     * @mbggenerated
     */
    List<CinemaMtime> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema_mtime
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CinemaMtime record);
}
