package com.family.grabserver.mapper;

import com.family.grabserver.entity.CinemamovieMaoyan;

import java.util.List;

public interface CinemamovieMaoyanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinemamovie_maoyan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinemamovie_maoyan
     *
     * @mbggenerated
     */
    int insert(CinemamovieMaoyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinemamovie_maoyan
     *
     * @mbggenerated
     */
    CinemamovieMaoyan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinemamovie_maoyan
     *
     * @mbggenerated
     */
    List<CinemamovieMaoyan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinemamovie_maoyan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CinemamovieMaoyan record);
}
