package com.family.grabserver.mapper;

import com.family.grabserver.entity.MaoyanCinema;

import java.util.List;

public interface MaoyanCinemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maoyan_cinema
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maoyan_cinema
     *
     * @mbggenerated
     */
    int insert(MaoyanCinema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maoyan_cinema
     *
     * @mbggenerated
     */
    MaoyanCinema selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maoyan_cinema
     *
     * @mbggenerated
     */
    List<MaoyanCinema> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maoyan_cinema
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MaoyanCinema record);
}