package com.family.grabserver.mapper;

import com.family.grabserver.entity.MovieShowingMaoyan;

import java.util.List;

public interface MovieShowingMaoyanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_showing_maoyan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_showing_maoyan
     *
     * @mbggenerated
     */
    int insert(MovieShowingMaoyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_showing_maoyan
     *
     * @mbggenerated
     */
    MovieShowingMaoyan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_showing_maoyan
     *
     * @mbggenerated
     */
    List<MovieShowingMaoyan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_showing_maoyan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MovieShowingMaoyan record);
}