package com.family.grabserver.mapper;

import com.family.grabserver.entity.Moviecoming;

import java.util.List;

public interface MoviecomingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviecoming
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviecoming
     *
     * @mbggenerated
     */
    int insert(Moviecoming record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviecoming
     *
     * @mbggenerated
     */
    Moviecoming selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviecoming
     *
     * @mbggenerated
     */
    List<Moviecoming> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviecoming
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Moviecoming record);
}