package com.family.grabserver.mapper;

import com.family.grabserver.entity.MovieshowingMaoyan;

import java.util.List;

public interface MovieshowingMaoyanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieshowing_maoyan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieshowing_maoyan
     *
     * @mbggenerated
     */
    int insert(MovieshowingMaoyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieshowing_maoyan
     *
     * @mbggenerated
     */
    MovieshowingMaoyan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieshowing_maoyan
     *
     * @mbggenerated
     */
    List<MovieshowingMaoyan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieshowing_maoyan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MovieshowingMaoyan record);
}
