package com.family.grabserver.mapper;

import com.family.grabserver.entity.MovieComing;

import java.util.List;

public interface MovieComingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_coming
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_coming
     *
     * @mbggenerated
     */
    int insert(MovieComing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_coming
     *
     * @mbggenerated
     */
    MovieComing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_coming
     *
     * @mbggenerated
     */
    List<MovieComing> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_coming
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MovieComing record);
}