package com.family.grabserver.mapper;

import com.family.grabserver.entity.ShowplanMaoyan;

import java.util.List;

public interface ShowplanMaoyanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showplan_maoyan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showplan_maoyan
     *
     * @mbggenerated
     */
    int insert(ShowplanMaoyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showplan_maoyan
     *
     * @mbggenerated
     */
    ShowplanMaoyan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showplan_maoyan
     *
     * @mbggenerated
     */
    List<ShowplanMaoyan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showplan_maoyan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShowplanMaoyan record);
}