package com.family.grabserver.mapper;

import com.family.grabserver.entity.ShowplanMtime;

import java.util.List;

public interface ShowplanMtimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showplan_mtime
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showplan_mtime
     *
     * @mbggenerated
     */
    int insert(ShowplanMtime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showplan_mtime
     *
     * @mbggenerated
     */
    ShowplanMtime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showplan_mtime
     *
     * @mbggenerated
     */
    List<ShowplanMtime> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table showplan_mtime
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShowplanMtime record);
}