package com.family.grabserver.mapper;

import com.family.grabserver.entity.ShowPlanMaoyan;

import java.util.List;

public interface ShowPlanMaoyanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_plan_maoyan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_plan_maoyan
     *
     * @mbggenerated
     */
    int insert(ShowPlanMaoyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_plan_maoyan
     *
     * @mbggenerated
     */
    ShowPlanMaoyan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_plan_maoyan
     *
     * @mbggenerated
     */
    List<ShowPlanMaoyan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table show_plan_maoyan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShowPlanMaoyan record);
}