package com.family.webserver.mapper;

import com.family.webserver.entity.City;

import java.util.List;

public interface CityMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city
   *
   * @mbggenerated Sun Dec 13 20:33:04 CST 2015
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city
   *
   * @mbggenerated Sun Dec 13 20:33:04 CST 2015
   */
  int insert(City record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city
   *
   * @mbggenerated Sun Dec 13 20:33:04 CST 2015
   */
  City selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city
   *
   * @mbggenerated Sun Dec 13 20:33:04 CST 2015
   */
  List<City> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city
   *
   * @mbggenerated Sun Dec 13 20:33:04 CST 2015
   */
  int updateByPrimaryKey(City record);
}
