package com.family.webserver.mapper;

import com.family.webserver.entity.CityArea;

import java.util.List;

public interface CityAreaMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city_area
   *
   * @mbggenerated Sun Dec 13 20:33:05 CST 2015
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city_area
   *
   * @mbggenerated Sun Dec 13 20:33:05 CST 2015
   */
  int insert(CityArea record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city_area
   *
   * @mbggenerated Sun Dec 13 20:33:05 CST 2015
   */
  CityArea selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city_area
   *
   * @mbggenerated Sun Dec 13 20:33:05 CST 2015
   */
  List<CityArea> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table city_area
   *
   * @mbggenerated Sun Dec 13 20:33:05 CST 2015
   */
  int updateByPrimaryKey(CityArea record);
}
