package com.family.webserver.mapper;

import com.family.webserver.entity.HomeCityHotMovie;
import com.family.webserver.entity.Movieshowing;

import java.util.List;

public interface MovieshowingMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table movieshowing
   *
   * @mbggenerated Sat Dec 12 22:05:44 CST 2015
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table movieshowing
   *
   * @mbggenerated Sat Dec 12 22:05:44 CST 2015
   */
  int insert(Movieshowing record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table movieshowing
   *
   * @mbggenerated Sat Dec 12 22:05:44 CST 2015
   */
  Movieshowing selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table movieshowing
   *
   * @mbggenerated Sat Dec 12 22:05:44 CST 2015
   */
  List<Movieshowing> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table movieshowing
   *
   * @mbggenerated Sat Dec 12 22:05:44 CST 2015
   */
  int updateByPrimaryKey(Movieshowing record);


  List<HomeCityHotMovie> selectHomeHotMoviesByCity(Integer cityId);
}
