package com.family.webserver.mapper;

import com.family.webserver.entity.Showplan;

import java.util.List;

public interface ShowplanMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table showplan
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table showplan
   *
   * @mbggenerated
   */
  int insert(Showplan record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table showplan
   *
   * @mbggenerated
   */
  Showplan selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table showplan
   *
   * @mbggenerated
   */
  List<Showplan> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table showplan
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(Showplan record);
}
